cmdline.cc
docs/mold.1

Fixes https://github.com/rui314/mold/issues/53

Ignore --no-add-needed

---

README.md

Signed-off-by: Artur Sinila <freesoftware@logarithmus.dev>

README.md: add guide to using mold with GCC via -B option

---

Makefile

Huge thanks to you for creating this amazing program!
This PR contains various small fixes to `Makefile`, namely:
- assign `GIT_HASH` only if it hasn't been assigned yet (useful when building an extracted tarball instead of `git clone`, e. g. [Void Linux package](https://github.com/void-linux/void-packages/blob/9cd75f36185341ec664e06072c10c6fa353fa1fb/srcpkgs/mold/template))
- Respect `LDFLAGS`
- Add `SYSTEM_MIMALLOC` variable to link against system-wide installed `mimalloc` shared library (useful for packaging)
- Replace `CFLAGS` with `CXXFLAGS` (why did you even use CFLAGS, `mold` is written in C++ after all)
- Respect `$DESTDIR`, more info: https://www.gnu.org/prep/standards/html_node/DESTDIR.html (again useful for packaging)

Various fixes in Makefile

---

Makefile

A tiny follow-up of https://github.com/rui314/mold/pull/62

Makefile: add $(DESTDIR) to strip

---

.github/workflows/ci.yml

[CI] Test code with GCC 11.1.0

---

.gitignore

Signed-off-by: Artur Sinila <freesoftware@logarithmus.dev>

.gitignore: add .cache & compile_commands.json (for clangd)

---

output_chunks.cc

Ensure correct visibility of symbols in .dynsym section

---

output_chunks.cc
test/ifunc-export.sh

This is a partial revert of dd04357

Do not replace IFUNC with FUNC in .dynsym

---

test/run.sh

Signed-off-by: Artur Sinila <freesoftware@logarithmus.dev>

Fix test/run.sh for cases when /usr/bin/ld -> /usr/bin/mold

---

README.md

While reading the README I realized a few typos (nubmers, langauge, Markle) so I took the liberty of running the README through Grammarly to spot more errors and hence this PR!

Fix README typos and improved syntax a bit

---

build-static.sh

Closes: https://github.com/rui314/mold/issues/138
Signed-off-by: Sam James <sam@gentoo.org>

build: fix build-static.sh (adapt to Makefile changes: respect LDFLAGS)

---

Makefile

add missing -lrt flag to Makefile

---

elf/subprocess.cc
filepath.cc

This is a draft pull request that tries to address the concerns raised in #207. I have retained the part of @SvenJo's commit that remains unchanged, and added my suggested overhaul of ` get_current_dir()` and `get_realpath()` as additional commits on top.
@rui314, @SvenJo, please let me know what you think.

Fix handling of path buffer sizes

---

elf/cmdline.cc

The exact same four lines of code exist a few lines below this hunk.

Remove duplicate code

---

elf/cmdline.cc

[ELF] Fix parsing of --no-dynamic-linker on command line

---

elf/output-file.cc
macho/output-file.cc

Please show errno for ftruncate and fchmod also.

Show errno for ftruncate and fchmod

---

mold.h

Add missing `#include <bit>`

---

README.md

Patch by Josh Triplett
https://salsa.debian.org/pkg-llvm-team/mold/-/merge_requests/8/diffs
Signed-off-by: Sylvestre Ledru <sylvestre@debian.org>

Readme: Improve the wording

---

elf/cmdline.cc

GNU ld aliases these to `-Bdynamic` and `-Bstatic` respectively.
Signed-off-by: Sefa Eyeoglu <contact@scrumplex.net>

[ELF] Add --dy and --dn aliases

---

test/elf/riscv-hello-dynamic.sh
test/elf/riscv-hello-static.sh

Signed-off-by: Dawid Jurczak <dawid_jurek@vp.pl>

[ELF][RISC-V] Do not hardcode GCC version in tests

---

test/elf/gdb-index-dwarf2.sh
test/elf/gdb-index-dwarf3.sh
test/elf/gdb-index-dwarf4.sh

Use the mode, otherwise one can be asked things like:
Quit anyway? (y or n)
which make the test stuck.

Use -batch mode for gdb tests.

---

elf/dwarf.cc
elf/elf.h
elf/input-files.cc
elf/mold.h
elf/output-chunks.cc

Various fixes for gdb index support (#444). I can re-link entire LibreOffice and gdb seems to work fine. The commits here mostly depend on previous ones, I can't easily submit them separately.

Gdb index fixes

---

elf/dwarf.cc
test/elf/gdb-index-compress-output.sh
test/elf/gdb-index-dwarf2.sh
test/elf/gdb-index-dwarf3.sh
test/elf/gdb-index-dwarf4.sh
test/elf/gdb-index-dwarf5.sh

I see you pushed a fix for #467 just at the same time, but I think the other two commits are still useful.

Gdb index address size

---

README.md

README: GCC 12.1 is already released

---

elf/output-chunks.cc

This is an unusual scenario, but it can happen on Arch Linux, where
apparently even crt1.o has no .debug_info . So if one for whatever
reason omits -g for all compilations and then uses --gdb-index,
mold aborts.

don't abort with --gdb-index if there's no .debug_info

---

elf/cmdline.cc
elf/input-files.cc
elf/main.cc
elf/mold.h
elf/passes.cc
test/elf/note-property.sh
test/elf/shlib-undefined.sh

I believe this fixes #526. 
I hope this covers all cases. If not, let me know and I can look into it some more!
Signed-off-by: Robert Bartlensky <bartlensky.robert@gmail.com>

Implement `--(no-)allow-shlib-undefined.

---

install-build-deps.sh

Add support for Arch Linux in the script for installing dependencies
Signed-off-by: Lorena R. Contreras<arturo211234@gmail.com>

Add support to install deps on Arch

---

docs/mold.1
elf/cmdline.cc
elf/linker-script.cc
elf/main.cc
elf/mold.h
elf/relocatable.cc
test/elf/dynamic-list.sh
test/elf/dynamic-list2.sh
test/elf/dynamic-list3.sh

See descriptions in commit messages.
Closes: #532

[elf] Implement --export-dynamic-symbol[-list]. 

---

CMakeLists.txt

Signed-off-by: Vincent Torri <vtorri@outlook.fr>

Windows: does not test pow() when compiling also with mingw

---

CMakeLists.txt

Signed-off-by: Vincent Torri <vtorri@outlook.fr>

Windows: define the version of header files to Windows 10

---

update-git-hash.py

As per packagers recommendation here https://github.com/Homebrew/homebrew-core/pull/108346#discussion_r949151369

Use portable shebang for python3 in update-git-hash.py

---

elf/arch-riscv.cc

This patch completes the R_RISCV_CALL_PLT relaxation function, as it is done in [LLVM lld](https://github.com/llvm/llvm-project/blob/main/lld/ELF/Arch/RISCV.cpp#L554). However, I don't know if there is any case where auipc+jalr can be relaxed to c.j.

[RISCV] Relax AUIPC+JALR to C.JAL or C.J

---

elf/arch-riscv.cc

This patch checked all the relocation ranges we currently support are valid, but I have no idea how to test them.

[RISCV] Check relocation range

---

test/elf/tls-gd2.sh
test/elf/tls-ie.sh
test/elf/tls-large-tbss.sh
test/elf/tls-ld-noplt.sh
test/elf/tls-ld.sh
test/elf/tls-le.sh
test/elf/tls-nopic.sh
test/elf/tls-pic.sh

Related to https://github.com/rui314/mold/issues/461

[RISCV] Enable tls tests for RV32 and RV64

---

test/elf/tls-gd-noplt.sh

Sorry for the frequent trivial PRs, but I missed a test case.

[RISCV] Enable tls-gd-noplt tests for RV32 and RV64

---

test/elf/compress-debug-sections-zstd.sh
test/elf/compress-debug-sections.sh
test/elf/compressed-debug-info.sh
test/elf/dead-debug-sections.sh
test/elf/gdb-index-compress-output.sh
test/elf/gdb-index-dwarf2.sh
test/elf/gdb-index-dwarf3.sh
test/elf/gdb-index-dwarf4.sh
test/elf/gdb-index-dwarf5.sh
test/elf/gnu-unique.sh
test/elf/init-array-readonly.sh
test/elf/pack-dyn-relocs-relr.sh
test/elf/run-clang.sh

`which` is not always installed.
I also noticed `perl` was used in a single test, that could be replaced with `sed`.

Don't use which(1) or perl

---

elf/arch-sparc64.cc

sparc64: remove unused code

---

CMakeLists.txt

remove duplicate in CMakeLists.txt

---

elf/cmdline.cc

Closes: https://github.com/rui314/mold/issues/755

[elf] Update push/pop-state documentation.

---

test/elf/compressed-debug-info.sh

remove extra OK message from a test

---

test/elf/tlsdesc-import.sh
test/elf/tlsdesc-static.sh
test/elf/tlsdesc.sh

tests: use skip function call when possible

---

elf/subprocess.cc

Since /proc isn't mounted by default in FreeBSD. Trying to read /proc/self/exe just crashes the program, so instead we have to use sysctl to get the path to the program. 
Signed-off-by: Topi Kainulainen <topikainulainen@protonmail.com>

Fix /proc/self behaviour on FreeBSD

---

elf/input-files.cc
mold.h

Explanation in commit message.

Some trivial optimizations

---

docs/mold.1

man: fixes a couple of typos

---

archive-file.h
elf/cmdline.cc
elf/input-files.cc
elf/lto-unix.cc
elf/mold.h
elf/output-chunks.cc
elf/passes.cc
macho/main.cc

fix typos in comments and help string

---

elf/cmdline.cc

ignore BFD linker argument --max-cache-size=size

---

README.md

Thank you for adding the logo.
I found a few mistakes and will correct them.

Adjust the image ratio and fix the alt attribute.

---

test/elf/riscv64_obj-compatible.sh

[RISCV] Fix riscv64_obj-compatible

---

common/Dockerfile
install-build-deps.sh

Note: I didn't test this locally, I am expecting the CI to test this, so let the CI run this before merging ;)

Removing remaining openssl mentions following the move to Blake3.

---

install-build-deps.sh

Summary
----
This PR adds support for [Artix OS](https://artixlinux.org/).

Add support for Artix OS

---

elf/mold-wrapper.c

Fixes issue 1153.
Signed-off-by: Andreas Schwab <schwab@suse.de>

mold-wrapper: also wrap posix_spawnp

---

common/output-file-unix.h

Using ftruncate() creates holes inside files, that on first (write) page fault gets allocated an actual disk block.  There are several disadvantages with this:
- Allocating block one-by-one is slower than doing it all at once.
- As we write to the output in parallel the write order is not exactly sequential.  The allocated blocks can also be out-of-order and make the on-disk representation fragmented.
Instead, use posix_fallocate() which allocates a contiguous on-disk block (if possible).  It's arguably a better fit for linker output, since holes are unlikely to be present after writing all the output (any contiguous zeroes should just go into .bss).
I benchmarked this by linking mold with debug symbols.  On an 8-core desktop, it is 5% (1.0s -> 0.95s) faster, but on a 64-core workstation …

Use fallocate when creating a new output

---

common/common.h

Prior to this change, links on Windows were failing with:
mold: fatal: <input file>: CreateFileMapping failed: 5
"5" is the Windows error code for ERROR_ACCESS_DENIED.
Use native Windows file API in MappedFile. Create read only mapping with FILE_MAP_COPY view because the file mapping contents may be modified in process but should not be written back.
On Windows, it is important that files are opened in "binary" mode to avoid automatic "text" mode conversions which can result in "corrupted" input/output.

Fixes and improvements to Windows file handling and memory mapping

---

.github/workflows/ci.yml
elf/lto-unix.cc

Fix cross-compile lto on MacOS

---

src/cmdline.cc

Linux upstream has reverted commit `2a010c412853 ("fs: don't block i_writecount during exec")` and the change is merged in the 6.13 cycle. This means the executable overwriting behavior can be restored on Linux kernel version 6.13 or later.
Note that there is probably not much we can do for 6.11 / 6.12 kernels. Although the reversion is backported, many distros do not use upstream sub-version numbers which means we cannot determine whether the kernel has this reversion based on its version number.
All of the builtin tests passed (via `ninja test -C build`):
```
100% tests passed, 0 tests failed out of 386
Total Test time (real) =  16.50 sec
The following tests did not run:
49 - x86_64-arch-x86_64-z-rewrite-endbr3 (Skipped)
76 - x86_64-compressed-debug-info (Skipped)
84 - …
```

Restore executable overwriting behavior on Linux 6.13 or later

---

install-build-deps.sh

It's just a popular arch fork, so put it in the arch block

Update install-build-deps.sh to know what cachyos is

---

src/arch-riscv.cc

Fixes #1474
Signed-off-by: Andreas Schwab <schwab@suse.de>

[RISC-V] Fix range checks for HI20/LO12 reloc addends
